version: 2.1
jobs:
  maven-build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          command: mvn package
      - store_test_results:
          path: target/surefire-reports
  maven-release:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: set environment variables
          command: 'git config --global user.email "roman.marcu@gmail.com" \ 
          && git config --global user.name "RomanMarcu" \
          && git config --global commit.gpgsign true \
          && git config --global user.signingkey 86D77D745FB28C21'
      - run:
          name: prepare release
          command: mvn --batch-mode release:clean release:prepare
      - run:
          name: perform release
          command: mvn --batch-mode release:perform
workflows:
  commit:
    jobs:
      - maven-build:
          filters:
            branches:
              ignore: /release.*/
  release:
    jobs:
      - maven-release:
          filters:
            branches:
              only: /release.*/