version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          command: mvn package
      - store_test_results:
          path: target/surefire-reports
  release:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: GPG configurations
          command: 'echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --no-tty --import --yes'
      - run:
          name: Setup git
          command: 'git config --global user.email "roman.marcu@gmail.com" \ 
          && git config --global user.name "Roman Marcu" \
          && git config --global user.signingkey $GPG_SIGNING_KEY_ID'
      - run:
          name: Perform release
          command: |
            echo "Starting new release..."
            MVN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "Preparing release from version ${MVN_VERSION}..."
            mvn --batch-mode release:clean release:prepare -P release -DscmCommentPrefix="[skip ci]"
            if [ -f "release.properties" ]; then
              #echo "true" >> releasePropsCreated
              echo "Generated release.properties: ..."
              cat release.properties
            fi
            echo "Performing release..."
            mvn --batch-mode release:perform -P release -s .circleci/maven_settings.xml
            echo "Release completed"
            MVN_VERSION_NEXT_DEV=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "New development version ${MVN_VERSION_NEXT_DEV}"

release-tag-only: &release-tag-only
  filters:
    tags:
      only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
    branches:
      only:
        - main
not-release-tag: &not-release-tag
  filters:
    tags:
      ignore: /^v[0-9]+\.[0-9]+\.[0-9]+$/
    branches:
      ignore: /.*/

workflows:
  commit:
    jobs:
      - build_and_test:
          <<: *not-release-tag
  release:
    jobs:
      - build_and_test:
          <<: *release-tag-only
      - release:
          <<: *release-tag-only
          requires:
            - build_and_test
