version: 2.1
jobs:
  maven-build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          command: mvn package
      - store_test_results:
          path: target/surefire-reports
  maven-release:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          command: mvn release:clean release:prepare
      - run:
          command: mvn release:perform
workflows:
  build-and-package:
    jobs:
      - maven-build
  release:
    jobs:
      - maven-release