version: 2.1
jobs:
  maven-build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          command: mvn package
      - store_test_results:
          path: target/surefire-reports
  maven-release:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          command: mvn --batch-mode release:clean release:prepare
      - run:
          command: mvn --batch-mode release:perform
workflows:
  build-and-package:
    jobs:
      - maven-build
  release:
    jobs:
      - maven-release:
          requires:
            - maven-build
          filters:
            branches:
              only: /^main$/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

