version: 2.1
jobs:
  maven-build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          command: mvn package
      - store_test_results:
          path: target/surefire-reports
  maven-release:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:ofo1klWl56Pn8SKWhwgI0KpQ+mVIICcKv8P388G3xyw"
      - checkout
      - run:
          name: GPG configurations
          command: 'echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --no-tty --import --yes'
      - run:
          name: Perform release
          command: |
            echo "Starting new release..."
            ssh-keyscan github.com
            MVN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "Preparing release from version ${MVN_VERSION}..."
            mvn --batch-mode release:clean release:prepare  -Prelease -DscmCommentPrefix="[skip ci] [maven-release-plugin] "
            if [ -f "release.properties" ]; then
              #echo "true" >> releasePropsCreated
              echo "Generated release.properties: ..."
              cat release.properties
            fi
            echo "Performing release..."
            mvn --batch-mode release:perform -Prelease -s .circleci/maven_settings.xml
            echo "Release completed"
            MVN_VERSION_NEXT_DEV=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "New development version ${MVN_VERSION_NEXT_DEV}"
workflows:
  commit:
    jobs:
      - maven-build:
          filters:
            branches:
              ignore: /release.*/
  release:
    jobs:
      - maven-release:
          filters:
            branches:
              only: /release.*/