version: 2.1
orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.18

jobs:
  maven-build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          command: mvn package
      - store_test_results:
          path: target/surefire-reports

workflows:
  commit:
    jobs:
      - maven-build:
          filters:
            branches:
              ignore: /release.*/
  release:
    jobs:
      - circleci-maven-release-orb/run-maven-release:
          ssh-fingerprints: "SHA256:D53tXKajLodz4uKksk/fhRlUtLl3DwgSNxoK5n+lJR8"
          filters:
            branches:
              only: /release.*/
