version: 2.1
jobs:
  maven-build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          command: mvn package
      - store_test_results:
          path: target/surefire-reports
  maven-prepare-release:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: GPG configurations
          command: 'echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import'
      - run:
          name: set environment variables
          command: 'git config --global user.email "roman.marcu@gmail.com" \ 
          && git config --global user.name "RomanMarcu" \
          && git config --global user.signingkey $GPG_SIGNING_KEY_ID'
      - run:
          name: prepare release
          command: mvn --batch-mode release:clean release:prepare
  maven-release:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: setTTY
          command: 'export GPG_TTY=$(tty)'
      - run:
          name: GPG configurations
          command: 'echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --passphrase $GPG_SIGNING_PASS --import'
      - run:
          name: set environment variables
          command: 'git config --global user.email "roman.marcu@gmail.com" \ 
          && git config --global user.name "RomanMarcu" \
          && git config --global user.signingkey $GPG_SIGNING_KEY_ID'
      - run:
          name: perform release
          command: mvn --batch-mode release:perform
workflows:
  commit:
    jobs:
      - maven-build:
          filters:
            branches:
              ignore: /release.*/
  release:
    jobs:
      - maven-prepare-release:
          filters:
            branches:
              only: /release.*/
      - maven-release:
          filters:
            branches:
              only: /testrelease.*/
