version: 2.1
jobs:
  maven-build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          command: mvn package
      - store_test_results:
          path: target/surefire-reports
  maven-release:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          command: mvn --batch-mode release:clean release:prepare
      - run:
          command: mvn --batch-mode release:perform
workflows:
  commit:
    jobs:
      - maven-build:
          filters:
            branches:
              ignore: /^release$/
  release:
    jobs:
      - maven-release:
          filters:
            branches:
              only: /^release$/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

